Fix boost import (#69)
* Fix boost import

Since very recently, builds using this repo have started failing with
errors due to the Boost dependency:
```
ERROR: /home/vscode/.cache/bazel/_bazel_vscode/e9b5149ef40c40531841044f5a70254d/external/com_github_3rdparty_stout/BUILD.bazel:62:11: @com_github_3rdparty_stout//:stout depends on @boost//:variant in repository @boost which failed to fetch. no such package '@boost//': java.io.IOException: Error downloading [https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.gz] to /home/vscode/.cache/bazel/_bazel_vscode/e9b5149ef40c40531841044f5a70254d/external/boost/temp13387589294389186013/boost_1_79_0.tar.gz: Checksum was 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff but wanted 273f1be93238a068aba4f9735a4a2b003019af067b9c183ed227780b8f36062c
```

We fix this error by upgrading to a newer version of the Boost repo. We
can't go beyond https://github.com/nelhage/rules_boost/pull/319 since it
breaks our Windows support; see: https://github.com/nelhage/rules_boost/issues/535

While we're here, also add a `.bazeliskrc`, which is important to have
this repo work with our modern Codespaces.

* Also fix MergeQueue config's windows check entry